title = "StyleGAN API"
version = "1.0.0"
description = "画像生成"
lossy = false
docs = true
redoc = true

[server]
gpu = -1
logger = "uvicorn"
tmp_dir = "./run"

[server.http]
forwarded = false

[server.http.cors]
enabled = true
origins = ["http://localhost:8000", "http://localhost:8080", "http://127.0.0.1:8000/"]

[server.limit]
min_delay = 1.5

[server.limit.block]
enabled = true
timeout = 10
poll = 0.25

[server.limit.rate]
enabled = true
window = 3600
max_request = 200

[models]
[models.mnist]
file = "models/MNIST32.hdf5"
relative = true
name = "MNIST"

[models.afhq]
file = "models/動物フリッカー.hdf5"
relative = true
name = "AFHQ"
gpu = false
lossy = true
[models.afhq.labels]
cat = "Cat"

