title = "StyleGAN API"
version = "1.0.0"
description = "画像生成"
lossy = false
docs = true
redoc = true

[server]
gpu = -1
logger = "uvicorn"
tmp = "./run"

[server.http]
proxy = false

[server.http.cors]
enabled = true
origins = ["http://localhost:8000", "http://localhost:8080", "http://127.0.0.1:8000/"]

[server.limit]
serial = true
delay = 1.5


[server.limit.block]
enabled = true
timeout = 10
poll = 0.25

[server.limit.rate]
enabled = true
max_rate = 1

[models]
toml_relative = true

[models.mnist]
file = "models/MNIST32.hdf5"
name = "MNIST"

[models.afhq]
file = "models/動物フリッカー.hdf5"
name = "AFHQ"
gpu = false
lossy = true
