title = "StyleGAN API"
version = "1.0.0"
description = "Simplified Web REST API of the StyleGANs"
lossy = false
docs = true
redoc = true

[server]
gpu = false
logger = "uvicorn"
tmp_dir = "./run"

[server.http]
forwarded = false

[server.http.cors]
enabled = true
origins = ["*://localhost:*", "*://127.0.0.1:*/"]

[server.limit]
min_delay = 1.5

[server.limit.block]
enabled = true
timeout = 10
poll = 0.25

[server.limit.concurrency]
enabled = true
max_concurrency = 8
max_queue = 24
timeout = 20
poll = 0.1

[server.limit.rate]
enabled = true
window = 3600
max_request = 200

[models]
[models.ffhq]
file = "../core/models/ffhq.hdf5"
relative = true
name = "FFHQ"
description = "Flickr-Faces-HQ"
lossy = true

[models.afhq]
file = "../core/models/afhq.hdf5"
relative = true
name = "AFHQ"
description = "Animal Faces-HQ"
lossy = true

[models.anime]
file = "../core/models/anime.hdf5"
relative = true
name = "Anime"
description = "Anime Faces"

[models.mnist]
file = "../core/models/mnist.hdf5"
relative = true
name = "MNIST"
description = "Hand-written grayscale digits from 0-9"
lossy = false
gpu = false

[models.k49]
file = "../core/models/k49.hdf5"
relative = true
name = "Kuzushiji-49"
description = "48 Hiragana characters and one Hiragana iteration mark"
lossy = false
gpu = false
